name: "Workflow"
#on:
#  push:
#    branches: [ "master" ]
#    tags:
#      - 'v*'
#  pull_request:
#    branches: [ "master" ]
on: workflow_dispatch
# Run monthly, at 00:00 on the 1st day of month.
#on:
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
        id: "todo"
